<h1>  “Love all, trust a few, do wrong to none.” – ...
“You call it madness, but I call it love.” – ...
“We can only learn to love by loving.” – ...
“A life lived in love will never be dull.” – ...
“Life is the flower for which love is the honey.” – ...
“All you need is love.” – ...
“True love stories never have endings.” !!!!   </h1>
<h2> Glad to see you here </h2>
